# https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-pre-commit
---
name: yamllint
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  lint:
    name: YAML Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: yamllint -s .

...
